### ISSUE TITLE
its wrong on win11

### ISSUE THREAD

**Issue by dforel** [keldaanCommunity/pokemonAutoChess#2362]
im use win11,
nodejs 20.16.0
when use npm install,
it show 

```
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm warn deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm error code 1
npm error path D:\workspace\game\pokemonAutoChess\edit\assetpack\node_modules\sharp
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
npm error sharp: Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.14.5/libvips-8.14.5-win32-x64.tar.br
npm error sharp: Please see https://sharp.pixelplumbing.com/install for required dependencies
npm error sharp: Installation error: aborted
npm error A complete log of this run can be found in: C:\Users\11\AppData\Local\npm-cache\_logs\2024-10-23T13_27_24_267Z-debug-0.log
npm error code 1
npm error path D:\workspace\game\pokemonAutoChess
npm error command failed
npm error command C:\WINDOWS\system32\cmd.exe /d /s /c npm run download-music && cd edit/assetpack && npm install
npm error A complete log of this run can be found in: C:\Users\11\AppData\Local\npm-cache\_logs\2024-10-23T13_26_54_504Z-debug-0.log


5626 http fetch POST 404 https://registry.npmmirror.com/-/npm/v1/security/advisories/bulk 151ms
5627 silly audit bulk request failed [object Object]
5628 http fetch POST 404 https://registry.npmmirror.com/-/npm/v1/security/audits/quick 26ms
5629 verbose audit error HttpErrorGeneral: 404 Not Found - POST https://registry.npmmirror.com/-/npm/v1/security/audits/quick - [NOT_IMPLEMENTED] /-/npm/v1/security/* not implemented yet
5629 verbose audit error     at D:\Users\11\AppData\Roaming\nvm\v20.16.0\node_modules\npm\node_modules\npm-registry-fetch\lib\check-response.js:95:15
5629 verbose audit error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
5629 verbose audit error     at async [getReport] (D:\Users\11\AppData\Roaming\nvm\v20.16.0\node_modules\npm\node_modules\@npmcli\arborist\lib\audit-report.js:336:21)
5629 verbose audit error     at async AuditReport.run (D:\Users\11\AppData\Roaming\nvm\v20.16.0\node_modules\npm\node_modules\@npmcli\arborist\lib\audit-report.js:106:19) {
5629 verbose audit error   headers: [Object: null prototype] {
5629 verbose audit error     server: [ 'Tengine' ],
5629 verbose audit error     date: [ 'Wed, 23 Oct 2024 13:27:01 GMT' ],
5629 verbose audit error     'content-type': [ 'application/json' ],
5629 verbose audit error     'transfer-encoding': [ 'chunked' ],
5629 verbose audit error     connection: [ 'keep-alive' ],
5629 verbose audit error     'strict-transport-security': [ 'max-age=5184000' ],
5629 verbose audit error     via: [ 'kunlun10.cn1182[,404666]' ],
5629 verbose audit error     'timing-allow-origin': [ '*' ],
5629 verbose audit error     eagleid: [ 'd35bf19e17296900210526121e' ],
5629 verbose audit error     'x-fetch-attempts': [ '1' ]
5629 verbose audit error   },
5629 verbose audit error   statusCode: 404,
5629 verbose audit error   code: 'E404',
5629 verbose audit error   method: 'POST',
5629 verbose audit error   uri: 'https://registry.npmmirror.com/-/npm/v1/security/audits/quick',
5629 verbose audit error   body: {
5629 verbose audit error     error: '[NOT_IMPLEMENTED] /-/npm/v1/security/* not implemented yet'
5629 verbose audit error   },
5629 verbose audit error   pkgid: undefined
5629 verbose audit error }
5630 silly audit error [object Object]
5631 silly audit report null
5632 silly tarball no local data for @biomejs/cli-win32-x64@https://registry.npmmirror.com/@biomejs/cli-win32-x64/-/cli-win32-x64-1.9.4.tgz. Extracting by manifest.
5633 silly tarball no local data for phaser3-rex-plugins@https://registry.npmmirror.com/phaser3-rex-plugins/-/phaser3-rex-plugins-1.80.9.tgz. Extracting by manifest.
5634 silly tarball no local data for phaser@https://registry.npmmirror.com/phaser/-/phaser-3.86.0.tgz. Extracting by manifest.
5635 silly tarball no local data for firebase@https://registry.npmmirror.com/firebase/-/firebase-10.14.1.tgz. Extracting by manifest.
5636 warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
5637 warn deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
5638 warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
5639 warn deprecated har-validator@5.1.5: this library is no longer supported
5640 warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
5641 warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
5642 warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
5643 warn deprecated pastebin-ts@1.3.0: Please use 'pastedeno' as your new Pastebin client
5644 http fetch GET 200 https://cdn.npmmirror.com/packages/%40biomejs/cli-win32-x64/1.9.4/cli-win32-x64-1.9.4.tgz 8544ms (cache miss)
5645 http fetch GET 200 https://cdn.npmmirror.com/packages/firebase/10.14.1/firebase-10.14.1.tgz 13865ms (cache miss)
5646 http fetch GET 200 https://cdn.npmmirror.com/packages/phaser/3.86.0/phaser-3.86.0.tgz 13890ms (cache miss)
5647 http fetch GET 200 https://cdn.npmmirror.com/packages/phaser3-rex-plugins/1.80.9/phaser3-rex-plugins-1.80.9.tgz 17112ms (cache miss)
5648 info run msgpackr-extract@3.0.3 install node_modules/msgpackr-extract node-gyp-build-optional-packages
5649 info run msgpackr-extract@3.0.3 install { code: 0, signal: null }
5650 info run @biomejs/biome@1.9.4 postinstall node_modules/@biomejs/biome node scripts/postinstall.js
5651 info run esbuild@0.23.1 postinstall node_modules/esbuild node install.js
5652 info run protobufjs@7.4.0 postinstall node_modules/protobufjs node scripts/postinstall
5653 info run @biomejs/biome@1.9.4 postinstall { code: 0, signal: null }
5654 info run protobufjs@7.4.0 postinstall { code: 0, signal: null }
5655 info run esbuild@0.23.1 postinstall { code: 0, signal: null }
5656 verbose stack Error: command failed
5656 verbose stack     at promiseSpawn (D:\Users\11\AppData\Roaming\nvm\v20.16.0\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:22:22)
5656 verbose stack     at spawnWithShell (D:\Users\11\AppData\Roaming\nvm\v20.16.0\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:124:10)
5656 verbose stack     at promiseSpawn (D:\Users\11\AppData\Roaming\nvm\v20.16.0\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:12:12)
5656 verbose stack     at runScriptPkg (D:\Users\11\AppData\Roaming\nvm\v20.16.0\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script-pkg.js:77:13)
5656 verbose stack     at runScript (D:\Users\11\AppData\Roaming\nvm\v20.16.0\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script.js:12:10)
5656 verbose stack     at async Install.exec (D:\Users\11\AppData\Roaming\nvm\v20.16.0\node_modules\npm\lib\commands\install.js:163:9)
5656 verbose stack     at async Npm.exec (D:\Users\11\AppData\Roaming\nvm\v20.16.0\node_modules\npm\lib\npm.js:207:9)
5656 verbose stack     at async module.exports (D:\Users\11\AppData\Roaming\nvm\v20.16.0\node_modules\npm\lib\cli\entry.js:74:5)
5657 verbose pkgid pokemon-auto-chess@5.6.0

```

**Comment by dforel** [comment]
i sorry ,its my network error,
when use proxy,it install good.
